GET http://localhost:3005/users

###

GET http://localhost:3005/users/65500ebd1bc968739c060b4e

###

POST http://localhost:3005/users
Content-Type: application/json

{
    "username" : "David",
    "email" : "justincalle@outlook.de",
    "password" : "123123"
}

### 

PATCH http://localhost:3005/users/65500ebd1bc968739c060b4e
Content-Type: application/json

{
    "username": "Hercules"
}

###

DELETE http://localhost:3005/users/6550b1ccf6ac063159b9b925

###

POST http://localhost:3005/users/login
Content-Type: application/json

{
    "username": "David",
    "password": "123123"
}

###

POST http://localhost:3005/chats/send
Content-Type: application/json

{
    "fromUsername": "Justin",
    "toUsername": "David",
    "text": "Wie gehts?"
}

###

GET http://localhost:3005/chats/retrieve?fromUsername=David&toUsername=justindavidcalle


###

GET http://localhost:3005/users/getallusernames

###

DELETE http://localhost:3005/chats/655d4c4c5397be0ff1ef4887